lampp:
  build: ./lampp/
  ports:
    - "80:80"
  volumes:
    - "./html:/var/www/html"
    - "./data/mysql/backup:/root/mysql/backup"
  volumes_from:
    - data
data:
  image: busybox:1
  volumes:
    - "./data/busybox/mysql:/var/lib/mysql"